
name: Hello World
on: 
  push:
    branches:
      - "**"

jobs:
  job_name:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    # - uses: actions/setup-node@v1
    - name: "run one command"
      run: echo "hello"
    - name: "multiple commands"
      run: |
        echo "one"
        echo "two"
  job_script:
    runs-on: ubuntu-latest
    steps:
    - name: bash script
      run: |
        echo ".????......${{ github.event.repository.name }}"
        if [ "${{ github.event.repository.name }}" == "local-github-actions" ]; then
          echo ".................YES    ${{ github.event.repository.name }}"
        fi


